export const BACKGROUND = require('./Pepsi_Boy_RGB_bg_1.png');
export const ICON_RECORD = require('./Record.png');
export const ICON_LYRIC = require('./Icon-Lyric.png');
export const ICON_NO_LYRIC = require('./Icon-NoLyric.png');
export const ICON_REFRESH = require('./Icon-Refresh.png');
export const LOGO_PEPSI = require('./Logo-Pepsi.png');
export const BACKGROUND_BOOTOM_TAB = require('./Pepsi_Boy_RGB_03.png');
export const BACKGROUND_HEADER = require('./Pepsi_Boy_RGB_04.png');
export const TEXT_PEPSI_MUSIC = require('./Text.png');
export const CARD_PEPSI_2_1x = require('./Image-Card_2_1x.png');
export const CARD_PEPSI_2 = require('./Image-Card_2.png');
export const TALEN = require('./talen.png');
export const HEADLINE_2 = require('./HEADLINE_2.png');
export const LEFT_BUTTON = require('./LeftButton.png');
export const RIGHT_BUTTON = require('./RightButton.png');
export const CENTER_BUTTON_1X = require('./CenterButton_1x.png');
export const CENTER_BUTTON_1_5X = require('./CenterButton_1_5x.png');
export const CENTER_BUTTON_2X = require('./CenterButton_2x.png');
export const LEFT_BUTTON_HOME = require('./ButtonLeft_Home.png');
export const RIGHT_BUTTON_HOME = require('./ButtonRight_Home.png');
export const INTRO_1 = require('./intro_1.png');
export const INTRO_2 = require('./intro_2.png');
export const INTRO_3 = require('./intro_3.png');
export const INTRO_4 = require('./intro_4.png');
export const INTRO_5 = require('./intro_5.png');
export const INTRO_6 = require('./intro_6.png');
export const LOA = require('./Loa.png');
export const AVATAR_1 = require('./Image-Avatar-1.png');
export const AVATAR_2_1X = require('./Image-Avatar-2_1x.png');
export const BANER_1 = require('./Image-Banner_1.png');
export const ANIMATION_1_1X = require('./Image-Animation_1_1x.png');
export const ANIMATION_2_1X = require('./Image-Animation_2_1x.png');
export const ANIMATION_3_1X = require('./Image-Animation_3_1x.png');
export const THUMB_MUSIC = require('./Image-ThumbMucsic.png');
export const THUMB_MUSIC_4X = require('./Image-ThumbMucsic_4x.png');
export const OPTION_1 = require('./Image-Option_1.png');
export const OPTION_2 = require('./Image-Option_2.png');
export const OPTION_3 = require('./Image-Option_3.png');
export const IMAGE_BORDER_TOP_1 = require('./Image-BorderTop_1.png')
export const IMAGE_BORDER_TOP_2 = require('./Image-BorderTop_2.png')
export const IMAGE_BORDER_TOP_3 = require('./Image-BorderTop_3.png')
export const IMAGE_RANK_1 = require('./Image-Rank_1.png')
export const IMAGE_RANK_2 = require('./Image-Rank_2.png')
export const IMAGE_RANK_3 = require('./Image-Rank_3.png')
export const IMAGE_RANK_4 = require('./Image-Rank_4.png')
export const BACKGROUND_RANK = require('./Image-Background_Rank.png')
export const AVATAR_RANK_1 = require('./Image-Avatar-Rank-1.png')
export const AVATAR_RANK_2 = require('./Image-Avatar-Rank-2.png')
export const AVATAR_RANK_3 = require('./Image-Avatar-Rank-3.png')
export const AVATAR_RANK_4 = require('./Image-Avatar-Rank-4.png')
export const IMAGE_BUC = require('./Image-Buc.png')
// export const ICON_EMAIL = require('./icon-email.png');
// export const ICON_FACEBOOK = require('./icon-facebook.png');
// export const ICON_GOOGLE = require('./icon-google.png');
// export const ICON_LOCK = require('./icon-lock.png');
// export const ICON_TWITTER = require('./icon-twitter.png');
